"""init db

迁移 ID: a3865d6ed01e
父迁移: 
创建时间: 2024-10-03 03:19:09.276427

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a3865d6ed01e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('nonebot_plugin_majsoul',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_majsoul_account_binding',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('majsoul_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_nonebot_plugin_majsoul_account_binding')),
    info={'bind_key': 'nonebot_plugin_majsoul'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonebot_plugin_majsoul_account_binding')
    # ### end Alembic commands ###
